services:
  web:
    image: dockette/web:php-82
    volumes:
      - ./:/srv
    ports:
      - 8080:80
    depends_on:
      - database
    environment:
      NETTE_DEBUG: 1

  database:
    image: mariadb:11.5
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: contributte
      MYSQL_PASSWORD: contributte
      MYSQL_DATABASE: contributte

  adminer:
    image: dockette/adminer:dg
    ports:
      - 8081:80
