name: "Nette Tester"

on:
  pull_request:

  push:
    branches: [ "*" ]

  schedule:
    - cron: "0 8 * * 1"

jobs:
  test84:
    name: "Nette Tester"
    uses: contributte/.github/.github/workflows/nette-tester-mysql.yml@master
    with:
      php: "8.4"
      database: tests

  test83:
    name: "Nette Tester"
    uses: contributte/.github/.github/workflows/nette-tester-mysql.yml@master
    with:
      php: "8.3"
      database: tests
